"""empty message

Revision ID: 30b2f9498a13
Revises: 59f6da070932
Create Date: 2023-10-04 17:59:14.975800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b2f9498a13'
down_revision: Union[str, None] = '59f6da070932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('emails', sa.String(), nullable=True),
    sa.Column('phones', sa.String(), nullable=True),
    sa.Column('postal_addresses', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('android_account_type', sa.String(), nullable=True),
    sa.Column('android_account_type_raw', sa.String(), nullable=True),
    sa.Column('android_account_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_display_name'), 'contacts', ['display_name'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.drop_index('ix_contact_id', table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prefix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suffix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emails', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phones', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_addresses', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('android_account_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('android_account_type_raw', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('android_account_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    op.create_index('ix_contact_id', 'contact', ['id'], unique=False)
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_display_name'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
